from __future__ import annotations

from app.models.design import DesignConfig, Host


def _emit_host_uplink_mapping(host: Host) -> str:
    lines = []
    for vmnic, uplink in host.uplink_mapping.items():
        lines.append(
            f'Add-VDSwitchPhysicalNetworkAdapter -VDSwitch $vds -VMHostPhysicalNic (Get-VMHostNetworkAdapter -VMHost $vmHost -Name "{vmnic}" -Physical) -UplinkPort "{uplink}" -Confirm:$false'
        )
    return "\n".join(lines)


def generate_powercli(config: DesignConfig) -> str:
    vmk = config.networking.vmkernel_portgroups
    guest_portgroups = "\n".join(
        f'$null = New-VDPortgroup -VDSwitch $vds -Name "{pg.name}" -VlanId {pg.vlan_id}'
        for pg in config.networking.guest_portgroups
    )

    host_blocks = []
    for host in config.hosts:
        host_blocks.append(
            f"""# Host: {host.name}
$existingHost = Get-VMHost -Name "{host.name}" -ErrorAction SilentlyContinue
if (-not $existingHost) {{
    $existingHost = Add-VMHost -Name "{host.address}" -Location $cluster -User $esxiUser -Password $esxiPassword -Force
}}

$vmHost = Get-VMHost -Name "{host.name}"
Add-VDSwitchVMHost -VDSwitch $vds -VMHost $vmHost

{_emit_host_uplink_mapping(host)}

$mgmtPg = Get-VDPortgroup -Name "{vmk.management.portgroup_name}"
$vmotionPg = Get-VDPortgroup -Name "{vmk.vmotion.portgroup_name}"
$storageAPg = Get-VDPortgroup -Name "{vmk.storage_a.portgroup_name}"
$storageBPg = Get-VDPortgroup -Name "{vmk.storage_b.portgroup_name}"

New-VMHostNetworkAdapter -VMHost $vmHost -PortGroup $mgmtPg -VirtualSwitch $vds -IP "{host.vmkernel_adapters.management.ip}" -SubnetMask "{host.vmkernel_adapters.management.subnet_mask}" -ManagementTrafficEnabled:$true
Get-VMHostNetwork -VMHost $vmHost | Set-VMHostNetwork -VMKernelGateway "{host.vmkernel_adapters.management.gateway}" -Confirm:$false

New-VMHostNetworkAdapter -VMHost $vmHost -PortGroup $vmotionPg -VirtualSwitch $vds -IP "{host.vmkernel_adapters.vmotion.ip}" -SubnetMask "{host.vmkernel_adapters.vmotion.subnet_mask}" -VMotionEnabled:$true
New-VMHostNetworkAdapter -VMHost $vmHost -PortGroup $storageAPg -VirtualSwitch $vds -IP "{host.vmkernel_adapters.storage_a.ip}" -SubnetMask "{host.vmkernel_adapters.storage_a.subnet_mask}"
New-VMHostNetworkAdapter -VMHost $vmHost -PortGroup $storageBPg -VirtualSwitch $vds -IP "{host.vmkernel_adapters.storage_b.ip}" -SubnetMask "{host.vmkernel_adapters.storage_b.subnet_mask}"
"""
        )

    return f"""# Generated by vSphere Bootstrap Designer
param(
    [Parameter(Mandatory=$true)][string]$vCenterServer,
    [Parameter(Mandatory=$true)][string]$vCenterUser,
    [Parameter(Mandatory=$true)][string]$vCenterPassword,
    [Parameter(Mandatory=$true)][string]$esxiUser,
    [Parameter(Mandatory=$true)][string]$esxiPassword
)

Set-PowerCLIConfiguration -InvalidCertificateAction Ignore -Confirm:$false | Out-Null
Connect-VIServer -Server $vCenterServer -User $vCenterUser -Password $vCenterPassword

$datacenter = Get-Datacenter -Name "{config.datacenter.name}" -ErrorAction SilentlyContinue
if (-not $datacenter) {{
    $datacenter = New-Datacenter -Name "{config.datacenter.name}"
}}

$cluster = Get-Cluster -Name "{config.cluster.name}" -ErrorAction SilentlyContinue
if (-not $cluster) {{
    $cluster = New-Cluster -Name "{config.cluster.name}" -Location $datacenter -HAEnabled:${str(config.cluster.ha_enabled).lower()} -DrsEnabled:${str(config.cluster.drs_enabled).lower()}
}}

$vds = Get-VDSwitch -Name "{config.distributed_switch.name}" -ErrorAction SilentlyContinue
if (-not $vds) {{
    $vds = New-VDSwitch -Name "{config.distributed_switch.name}" -Location $datacenter -NumUplinkPorts {len(config.distributed_switch.uplinks)} -Mtu {config.distributed_switch.mtu} -Version "{config.distributed_switch.version}"
}}

$null = New-VDPortgroup -VDSwitch $vds -Name "{vmk.management.portgroup_name}" -VlanId {vmk.management.vlan_id}
$null = New-VDPortgroup -VDSwitch $vds -Name "{vmk.vmotion.portgroup_name}" -VlanId {vmk.vmotion.vlan_id}
$null = New-VDPortgroup -VDSwitch $vds -Name "{vmk.storage_a.portgroup_name}" -VlanId {vmk.storage_a.vlan_id}
$null = New-VDPortgroup -VDSwitch $vds -Name "{vmk.storage_b.portgroup_name}" -VlanId {vmk.storage_b.vlan_id}
{guest_portgroups}

Set-VDPortgroup -VDPortgroup (Get-VDPortgroup -Name "{vmk.storage_a.portgroup_name}") -TeamingPolicy LoadBalanceLoadBased
Set-VDPortgroup -VDPortgroup (Get-VDPortgroup -Name "{vmk.storage_b.portgroup_name}") -TeamingPolicy LoadBalanceLoadBased

{chr(10).join(host_blocks)}

Disconnect-VIServer -Server $vCenterServer -Confirm:$false
"""
