# Generated by vSphere Bootstrap Designer
param(
    [Parameter(Mandatory=$true)][string]$vCenterServer,
    [Parameter(Mandatory=$true)][string]$vCenterUser,
    [Parameter(Mandatory=$true)][string]$vCenterPassword,
    [Parameter(Mandatory=$true)][string]$esxiUser,
    [Parameter(Mandatory=$true)][string]$esxiPassword
)

Set-PowerCLIConfiguration -InvalidCertificateAction Ignore -Confirm:$false | Out-Null
Connect-VIServer -Server $vCenterServer -User $vCenterUser -Password $vCenterPassword

$datacenter = Get-Datacenter -Name "DC01" -ErrorAction SilentlyContinue
if (-not $datacenter) {
    $datacenter = New-Datacenter -Name "DC01"
}

$cluster = Get-Cluster -Name "Compute-Cluster-01" -ErrorAction SilentlyContinue
if (-not $cluster) {
    $cluster = New-Cluster -Name "Compute-Cluster-01" -Location $datacenter -HAEnabled:$true -DrsEnabled:$true
}

$vds = Get-VDSwitch -Name "DSwitch-01" -ErrorAction SilentlyContinue
if (-not $vds) {
    $vds = New-VDSwitch -Name "DSwitch-01" -Location $datacenter -NumUplinkPorts 4 -Mtu 9000 -Version "8.0.0"
}

$null = New-VDPortgroup -VDSwitch $vds -Name "DVPG-MGMT" -VlanId 110
$null = New-VDPortgroup -VDSwitch $vds -Name "DVPG-VMOTION" -VlanId 120
$null = New-VDPortgroup -VDSwitch $vds -Name "DVPG-STORAGE-A" -VlanId 310
$null = New-VDPortgroup -VDSwitch $vds -Name "DVPG-STORAGE-B" -VlanId 311
$null = New-VDPortgroup -VDSwitch $vds -Name "DVPG-GUEST-PROD" -VlanId 210
$null = New-VDPortgroup -VDSwitch $vds -Name "DVPG-GUEST-DEV" -VlanId 211

Set-VDPortgroup -VDPortgroup (Get-VDPortgroup -Name "DVPG-STORAGE-A") -TeamingPolicy LoadBalanceLoadBased
Set-VDPortgroup -VDPortgroup (Get-VDPortgroup -Name "DVPG-STORAGE-B") -TeamingPolicy LoadBalanceLoadBased

# Host: esx01.lab.local
$existingHost = Get-VMHost -Name "esx01.lab.local" -ErrorAction SilentlyContinue
if (-not $existingHost) {
    $existingHost = Add-VMHost -Name "10.10.10.21" -Location $cluster -User $esxiUser -Password $esxiPassword -Force
}

$vmHost = Get-VMHost -Name "esx01.lab.local"
Add-VDSwitchVMHost -VDSwitch $vds -VMHost $vmHost
Add-VDSwitchPhysicalNetworkAdapter -VDSwitch $vds -VMHostPhysicalNic (Get-VMHostNetworkAdapter -VMHost $vmHost -Name "vmnic0" -Physical) -UplinkPort "Uplink1" -Confirm:$false
Add-VDSwitchPhysicalNetworkAdapter -VDSwitch $vds -VMHostPhysicalNic (Get-VMHostNetworkAdapter -VMHost $vmHost -Name "vmnic1" -Physical) -UplinkPort "Uplink2" -Confirm:$false
Add-VDSwitchPhysicalNetworkAdapter -VDSwitch $vds -VMHostPhysicalNic (Get-VMHostNetworkAdapter -VMHost $vmHost -Name "vmnic2" -Physical) -UplinkPort "Uplink3" -Confirm:$false
Add-VDSwitchPhysicalNetworkAdapter -VDSwitch $vds -VMHostPhysicalNic (Get-VMHostNetworkAdapter -VMHost $vmHost -Name "vmnic3" -Physical) -UplinkPort "Uplink4" -Confirm:$false

$mgmtPg = Get-VDPortgroup -Name "DVPG-MGMT"
$vmotionPg = Get-VDPortgroup -Name "DVPG-VMOTION"
$storageAPg = Get-VDPortgroup -Name "DVPG-STORAGE-A"
$storageBPg = Get-VDPortgroup -Name "DVPG-STORAGE-B"

New-VMHostNetworkAdapter -VMHost $vmHost -PortGroup $mgmtPg -VirtualSwitch $vds -IP "10.10.110.21" -SubnetMask "255.255.255.0" -ManagementTrafficEnabled:$true
Get-VMHostNetwork -VMHost $vmHost | Set-VMHostNetwork -VMKernelGateway "10.10.110.1" -Confirm:$false
New-VMHostNetworkAdapter -VMHost $vmHost -PortGroup $vmotionPg -VirtualSwitch $vds -IP "10.10.120.21" -SubnetMask "255.255.255.0" -VMotionEnabled:$true
New-VMHostNetworkAdapter -VMHost $vmHost -PortGroup $storageAPg -VirtualSwitch $vds -IP "10.10.310.21" -SubnetMask "255.255.255.0"
New-VMHostNetworkAdapter -VMHost $vmHost -PortGroup $storageBPg -VirtualSwitch $vds -IP "10.10.311.21" -SubnetMask "255.255.255.0"

# Host: esx02.lab.local
$existingHost = Get-VMHost -Name "esx02.lab.local" -ErrorAction SilentlyContinue
if (-not $existingHost) {
    $existingHost = Add-VMHost -Name "10.10.10.22" -Location $cluster -User $esxiUser -Password $esxiPassword -Force
}

$vmHost = Get-VMHost -Name "esx02.lab.local"
Add-VDSwitchVMHost -VDSwitch $vds -VMHost $vmHost
Add-VDSwitchPhysicalNetworkAdapter -VDSwitch $vds -VMHostPhysicalNic (Get-VMHostNetworkAdapter -VMHost $vmHost -Name "vmnic0" -Physical) -UplinkPort "Uplink1" -Confirm:$false
Add-VDSwitchPhysicalNetworkAdapter -VDSwitch $vds -VMHostPhysicalNic (Get-VMHostNetworkAdapter -VMHost $vmHost -Name "vmnic1" -Physical) -UplinkPort "Uplink2" -Confirm:$false
Add-VDSwitchPhysicalNetworkAdapter -VDSwitch $vds -VMHostPhysicalNic (Get-VMHostNetworkAdapter -VMHost $vmHost -Name "vmnic2" -Physical) -UplinkPort "Uplink3" -Confirm:$false
Add-VDSwitchPhysicalNetworkAdapter -VDSwitch $vds -VMHostPhysicalNic (Get-VMHostNetworkAdapter -VMHost $vmHost -Name "vmnic3" -Physical) -UplinkPort "Uplink4" -Confirm:$false

$mgmtPg = Get-VDPortgroup -Name "DVPG-MGMT"
$vmotionPg = Get-VDPortgroup -Name "DVPG-VMOTION"
$storageAPg = Get-VDPortgroup -Name "DVPG-STORAGE-A"
$storageBPg = Get-VDPortgroup -Name "DVPG-STORAGE-B"

New-VMHostNetworkAdapter -VMHost $vmHost -PortGroup $mgmtPg -VirtualSwitch $vds -IP "10.10.110.22" -SubnetMask "255.255.255.0" -ManagementTrafficEnabled:$true
Get-VMHostNetwork -VMHost $vmHost | Set-VMHostNetwork -VMKernelGateway "10.10.110.1" -Confirm:$false
New-VMHostNetworkAdapter -VMHost $vmHost -PortGroup $vmotionPg -VirtualSwitch $vds -IP "10.10.120.22" -SubnetMask "255.255.255.0" -VMotionEnabled:$true
New-VMHostNetworkAdapter -VMHost $vmHost -PortGroup $storageAPg -VirtualSwitch $vds -IP "10.10.310.22" -SubnetMask "255.255.255.0"
New-VMHostNetworkAdapter -VMHost $vmHost -PortGroup $storageBPg -VirtualSwitch $vds -IP "10.10.311.22" -SubnetMask "255.255.255.0"

Disconnect-VIServer -Server $vCenterServer -Confirm:$false

